[build-system]
requires = ["uv_build<0.13"]
build-backend = "uv_build"

[project]
name = "polycache"
version = "0.1.0"
description = "Cache function outputs to disk in a variety of native formats using a single flexible decorator"
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
  { name = "Raj Magesh Gauthaman", email = "polycache@raj-magesh.org" },
]
keywords = [
  "cache",
  "flexible",
  "extensible",
  "native formats",
  "decorator",
  "pickle",
  "numpy",
  "xarray",
  "netCDF4",
  "nibabel",
  "NIfTI",
  "MNE-Python",
  "EDF",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
urls = { source = "https://codeberg.org/raj-magesh/polycache" }
dependencies = []

[dependency-groups]
# TODO split these into groups based on utility, to allow separate installation
dev = [
  "ruff",
  "ty",
  "pytest",
  "sphinx",
  "furo",
  "sphinx-autodoc-typehints",
  "sphinx_readme",
  "numpy",
  "xarray",
  "netCDF4",
  "cf-xarray",
  "edfio",
  "nibabel",
  "Pillow",
  "mne",
]

[tool.uv]
required-environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
